Entry points ikz plugin
FAIRmat-NFDI/AreaA-data_modeling_and_schemas pull request #166
Opened 2024-05-28 12:19 UTC by aalbino2

@hampusnasstrom finally, they should be all there

2024-06-05 09:43 UTC, hampusnasstrom requested changes
Great work! I added some suggestions for descriptions where I knew what to write but there are some parsers where you could maybe add some. Do you use any of the configuration parameters? If not, we should probably remove them. I tried looking though the files but it was a bit hard with all the Ruff linting... If we have some more old code to refactor we could consider merging the Ruff formatting first. I didn't test that it installs and runs all your plugins as I assume you have already tested that.

2024-06-05 09:43 UTC, hampusnasstrom commented on IKZ_plugin/src/ikz_plugin/general/__init__.py
> +    description='Schema package defined using the new plugin mechanism.',
Add description:
```suggestion
    description='Schema package for general definitions used throughout IKZ.',
```

2024-06-05 09:43 UTC, hampusnasstrom commented on IKZ_plugin/src/ikz_plugin/movpe/movpe1/growth_excel/parser.py
> +        from nomad.search import search, MetadataPagination
Is there a reason you moved this to inside the parse function? We recently had some issued with these "hidden" imports in the central nomad.

2024-06-05 09:43 UTC, hampusnasstrom commented on IKZ_plugin/src/ikz_plugin/movpe/movpe2/growth_excel/__init__.py
> +    parameter: int = Field(0, description='Custom configuration parameter')
```suggestion
```

2024-06-05 09:43 UTC, hampusnasstrom commented on IKZ_plugin/src/ikz_plugin/movpe/movpe2/growth_excel/__init__.py
> +    description='Parser defined using the new plugin mechanism.',
Please fill

2024-06-05 09:43 UTC, hampusnasstrom commented on IKZ_plugin/src/ikz_plugin/movpe/movpe2/utils.py
> +    from nomad.datamodel.context import ClientContext, ServerContext
Again, is there a reason for moving the imports here? You have the same imports again in the next function.

2024-06-05 09:43 UTC, hampusnasstrom commented on IKZ_plugin/src/ikz_plugin/movpe/substrate/__init__.py
> +    parameter: int = Field(0, description='Custom configuration parameter')
```suggestion
```

2024-06-05 09:43 UTC, hampusnasstrom commented on IKZ_plugin/src/ikz_plugin/movpe/substrate/__init__.py
> +    description='Parser defined using the new plugin mechanism.',
Please fill

2024-06-05 09:43 UTC, hampusnasstrom commented on IKZ_plugin/src/ikz_plugin/pld/__init__.py
> +    parameter: int = Field(0, description='Custom configuration parameter')
```suggestion
```

2024-06-05 09:43 UTC, hampusnasstrom commented on IKZ_plugin/src/ikz_plugin/pld/__init__.py
> +    description='Schema package defined using the new plugin mechanism.',
```suggestion
    description='A package containing schemas for Pulsed Laser Deposition (PLD) done at IKZ.',
```

2024-06-05 09:43 UTC, hampusnasstrom commented on IKZ_plugin/src/ikz_plugin/pld/schema.py
> +from nomad.config import config
```suggestion
```

2024-06-05 09:43 UTC, hampusnasstrom commented on IKZ_plugin/src/ikz_plugin/pld/schema.py
> +configuration = config.get_plugin_entry_point('ikz_plugin.pld:pld_schema')
I don't use it at least
```suggestion
```

2024-06-05 09:43 UTC, hampusnasstrom commented on Lakeshore_plugin/src/lakeshore_plugin/hall/__init__.py
>      parameter: int = Field(0, description="Custom configuration parameter")
```suggestion
```

2024-06-05 09:43 UTC, hampusnasstrom commented on Lakeshore_plugin/src/lakeshore_plugin/hall/__init__.py
>      description="Schema package defined using the new plugin mechanism.",
```suggestion
    description="Schema package for Hall measurement definitions.",
```

2024-06-10 08:36 UTC, aalbino2 commented on IKZ_plugin/README.md
> +For some reason, you may want to avoid installation of the package with pip and plug this code to NOMAD in a more direct fashion:
removed

2024-06-10 08:36 UTC, aalbino2 commented on IKZ_plugin/README.md
> +    - 'ikz_plugin.czochralski:czochralski_multilog_parser'
yeah, I dropped this section..

2024-06-10 08:46 UTC, aalbino2 commented on IKZ_plugin/src/ikz_plugin/characterization/schema.py
> +)
I will leave it here, even if not used now

2024-06-10 09:55 UTC, merged